export const INIT_COLUMNS = 'INIT_COLUMNS'

export const CREATE_COLUMN_REQUEST = 'CREATE_COLUMN_REQUEST'
export const CREATE_COLUMN_SUCCESS = 'CREATE_COLUMN_SUCCESS'
export const CREATE_COLUMN_ERROR = 'CREATE_COLUMN_ERROR'

export const UPDATE_COLUMN_REQUEST = 'UPDATE_COLUMN_REQUEST'
export const UPDATE_COLUMN_SUCCESS = 'UPDATE_COLUMN_SUCCESS'
export const UPDATE_COLUMN_ERROR = 'UPDATE_COLUMN_ERROR'

export const DELETE_COLUMN_REQUEST = 'DELETE_COLUMN_REQUEST'
export const DELETE_COLUMN_SUCCESS = 'DELETE_COLUMN_SUCCESS'
export const DELETE_COLUMN_ERROR = 'DELETE_COLUMN_ERROR'

export const COLUMN_INSERT_TASK = 'COLUMN_INSERT_TASK'
export const COLUMN_REMOVE_TASK = 'COLUMN_REMOVE_TASK'
