export const INIT_COLUMNS = 'INIT_COLUMNS'
export const CREATE_COLUMN = 'CREATE_COLUMN'
export const MOVE_COLUMN = 'MOVE_COLUMN'
export const RENAME_COLUMN = 'RENAME_COLUMN'
export const DELETE_COLUMN = 'DELETE_COLUMN'

export const COLUMN_INSERT_TASK = 'COLUMN_INSERT_TASK'
export const COLUMN_REMOVE_TASK = 'COLUMN_REMOVE_TASK'
