export const INIT_PROJECTS = 'INIT_PROJECTS'
export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const RENAME_PROJECT_REQUEST = 'RENAME_PROJECT_REQUEST'
export const RENAME_PROJECT_SUCCESS = 'RENAME_PROJECT_SUCCESS'
export const FREEZE_PROJECT = 'FREEZE_PROJECT'
export const INSERT_COLUMN_PROJECT = 'INSERT_COLUMN_PROJECT'
export const DELETE_COLUMN_PROJECT = 'INSERT_COLUMN_PROJECT'

export const LOAD_STATISTICS_REQUEST = 'LOAD_STATISTICS_REQUEST';
export const LOAD_STATISTICS_SUCCESS = 'LOAD_STATISTICS_SUCCESS';
export const LOAD_STATISTICS_ERROR = 'LOAD_STATISTICS_ERROR';
