export const INIT_TASKS = 'INIT_TASKS'
export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'

export const MOVE_TASK_REQUEST = 'MOVE_TASK_REQUEST'
export const MOVE_TASK_SUCCESS = 'MOVE_TASK_SUCCESS'
export const MOVE_TASK_ERROR = 'MOVE_TASK_ERROR'

export const REORDER_TASK_REQUEST = 'REORDER_TASK_REQUEST'
export const REORDER_TASK_SUCCESS = 'REORDER_TASK_SUCCESS'
export const REORDER_TASK_ERROR = 'REORDER_TASK_ERROR'

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR'

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR'

export const ARCHIVE_TASK_REQUEST = 'ARCHIVE_TASK_REQUEST'
export const ARCHIVE_TASK_SUCCESS = 'ARCHIVE_TASK_SUCCESS'
export const ARCHIVE_TASK_ERROR = 'ARCHIVE_TASK_ERROR'
