export const INIT_TASKS = 'INIT_TASKS'
export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'

export const MOVE_TASK_REQUEST = 'MOVE_TASK_REQUEST'
export const MOVE_TASK_SUCCESS = 'MOVE_TASK_SUCCESS'
export const MOVE_TASK_ERROR = 'MOVE_TASK_ERROR'

export const REORDER_TASK_REQUEST = 'REORDER_TASK_REQUEST'
export const REORDER_TASK_SUCCESS = 'REORDER_TASK_SUCCESS'
export const REORDER_TASK_ERROR = 'REORDER_TASK_ERROR'

export const RENAME_TASK_REQUEST = 'RENAME_TASK_REQUEST'
export const RENAME_TASK_SUCCESS = 'RENAME_TASK_SUCCESS'
export const RENAME_TASK_ERROR = 'RENAME_TASK_ERROR'

export const CHANGE_TASK_DESCRIPTION_REQUEST = 'CHANGE_TASK_DESCRIPTION_REQUEST'
export const CHANGE_TASK_DESCRIPTION_SUCCESS = 'CHANGE_TASK_DESCRIPTION_SUCCESS'
export const CHANGE_TASK_DESCRIPTION_ERROR = 'CHANGE_TASK_DESCRIPTION_ERROR'

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR'

export const ARCHIVE_TASK_REQUEST = 'ARCHIVE_TASK_REQUEST'
export const ARCHIVE_TASK_SUCCESS = 'ARCHIVE_TASK_SUCCESS'
export const ARCHIVE_TASK_ERROR = 'ARCHIVE_TASK_ERROR'

export const TASK_SET_DEADLINE_REQUEST = 'TASK_SET_DEADLINE_REQUEST'
export const TASK_SET_DEADLINE_SUCCESS = 'TASK_SET_DEADLINE_SUCCESS'
export const TASK_SET_DEADLINE_ERROR = 'TASK_SET_DEADLINE_ERROR'

export const TASK_ADD_MARK_REQUEST = 'TASK_ADD_MARK_REQUEST'
export const TASK_ADD_MARK_SUCCESS = 'TASK_ADD_MARK_SUCCESS'
export const TASK_ADD_MARK_ERROR = 'TASK_ADD_MARK_ERROR'

export const TASK_REMOVE_MARK_REQUEST = 'TASK_REMOVE_MARK_REQUEST'
export const TASK_REMOVE_MARK_SUCCESS = 'TASK_REMOVE_MARK_SUCCESS'
export const TASK_REMOVE_MARK_ERROR = 'TASK_REMOVE_MARK_ERROR'
