export const INIT_USER = "INIT_USER";
export const STOP_TRACK_REQUEST = "STOP_TRACK_REQUEST";
export const STOP_TRACK_SUCCESS = "STOP_TRACK_SUCCESS";
export const STOP_TRACK_ERROR = "STOP_TRACK_ERROR";

export const START_TRACK_REQUEST  = "START_TRACK_REQUEST";
export const START_TRACK_SUCCESS  = "START_TRACK_SUCCESS";
export const START_TRACK_ERROR  = "START_TRACK_ERROR";
